### ISSUE TITLE
Is it possible to do something to compile this code in C++14 ?

### ISSUE THREAD

**Issue by Alauddin108** [makuke1234/PdfiumView#6]
Hi,
I am very interested to integrate this code in my application (Win32 C/C++). But, I can compile my existing code (big amount) only in C++14 and my own code is giving hundreds of error if I try to compile it with C++20. 

Regards,

Dr. Alauddin Biswas
Toronto, Canada

**Comment by makuke1234** [comment]
Yes, created a new branch to mitigate this

**Comment by makuke1234** [comment]
I'm sorry, but I found out that too much of the code needs to be rewritten in order to support C++14 (concepts, string_views etc need to be removed).
